### ISSUE TITLE
Removing a reference used to negate a nuget security violation

### ISSUE THREAD

**Issue by tcartwright** [dfederm/ReferenceTrimmer#107]
This relates mainly to transitive packages.

I really like this project, however I would like to make one suggestion. Where there are nuget security violations of NU1902;NU1903;NU1904 we add these packages to our Directory.Build.props and projects as overrides for the transitive packages in violation. 

The problem is that your tool removes those package overrides, and makes us fail our build again for the security violations.

Other than this issue, great tool. 💯

**Comment by tcartwright** [comment]
NVM, I should have finished RTFM.  We can disable those being removed using the NoWarn:

https://dfederm.com/removing-unused-dependencies-with-referencetrimmer/

**Comment by dfederm** [comment]
I would recommend using [Transitive Pinning](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management#transitive-pinning) instead of putting the PackageReferences in your Directory.Build.props.
