### ISSUE TITLE
Signal duplicate Project references

### ISSUE THREAD

**Issue by stan-sz** [dfederm/ReferenceTrimmer#27]
The implementation can be as simple as in `.targets`:

```xml
<Target Name="EnforceNoDuplciateItems" AfterTargets="ResolveProjectReferences">
  <RemoveDuplicates Inputs="@(ProjectReference)">
    <Output TaskParameter="HadAnyDuplicates" PropertyName="_HadAnyProjectReferenceDuplicates"/>
  </RemoveDuplicates>
  <Warning File="$(MSBuildProjectFile)" Text="Duplicate &lt;ProjectReference&gt; found" Condition="'$(_HadAnyProjectReferenceDuplicates)' == 'true'" />
</Target>
```

**Comment by stan-sz** [comment]
Based on https://github.com/dotnet/msbuild/issues/1541

**Comment by dfederm** [comment]
I believe NuGet already warns when there are duplicate PackageReferences

**Comment by stan-sz** [comment]
Indeed: https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1504

**Comment by stan-sz** [comment]
ProjectReference (and other ItemGroup duplicates) could possibly be covered by https://github.com/dotnet/msbuild/issues/1777

**Comment by stan-sz** [comment]
Given that there isn't a single coherent solution to this problem, I suggest reopening and adding this check to ReferenceTrimmer
