### ISSUE TITLE
Nuget or Chocolatey

### ISSUE THREAD

**Issue by sclarke81** [dfederm/ReferenceTrimmer#3]
Hi,

I'm just wondering if you've considered releasing this as a NuGet or Chocolatey package? I think it'd be super useful as both.

Thanks,

Stephen

**Comment by sclarke81** [comment]
There is a precedent for using NuGet for tools; Microsoft produces a package for [vswhere](https://www.nuget.org/packages/vswhere/).

Creating a dotnet global tool sounds like a good idea too.

Let me know if you'd like any input for creating NuGet or Chocolatey packages.

**Comment by dfederm** [comment]
Looks like a .NET Core Global Tool is out since I don't target .NET Core. A "normal" nuget tool package seems doable still though.

**Comment by dfederm** [comment]
I've uploaded the package to [NuGet](https://www.nuget.org/packages/ReferenceTrimmer/2.0.0), but I'm less familiar with Chocolatey (I don't use it myself, let alone create packages for it). Let me know if you still think Chocolatey would be significantly more useful than NuGet and I'll look more deeply into it.

**Comment by sclarke81** [comment]
Nice one! That's great. Actually, you'd need to do very little to put this on Chocolatey as well; you can reuse the same nupkg. Ideally, you'd change the `id` to be `reference-trimmer` and set `title` to be `ReferenceTrimmer` (Chocolatey has rules about package names). You should probably also complete the `description`.

If you want to test it out just [install chocolatey](https://chocolatey.org/install) then in the folder that contains your nupkg:

`choco install ReferenceTrimmer -s .` (or `choco install reference-trimmer -s .` if you've changed the `id`).

Chocolatey automatically adds the exe to your path. I've tried it with the current nupkg and it works! Obviously it's your call, but I think it'd be a minimal amount of effort and more and more people are using Chocolatey.
