### ISSUE TITLE
_ReferenceTrimmer_GetUsedAssemblyReferences.txt file breaks VS incremental builds

### ISSUE THREAD

**Issue by dfederm** [dfederm/ReferenceTrimmer#36]
In VS I'm seeing:

```
WARNING: Potential build performance issue in '<project>'. The project does not appear up-to-date after a successful build: Input AdditionalFiles item '<path-to-project>\obj\x64\Debug\_ReferenceTrimmer_GetUsedAssemblyReferences.txt' (1/18/2023 7:25:28 AM) has been modified since the last successful build started (1/18/2023 7:25:27 AM), not up-to-date. See https://aka.ms/incremental-build-failure.
```

**Comment by stan-sz** [comment]
A potential fix can be in the analyzer code to write the file only if the contents will be different. But, on top of that, we still have

https://github.com/dfederm/ReferenceTrimmer/blob/ce2befa1ac37ba4053e46ab1c096e6dc4f0f94c2/src/build/ReferenceTrimmer.targets#L16-L18

which is needed to ensure RT runs on accurate data (avoids stale file contents). Possibly the `BeforeTargets` can be removed and just rely on `CoreCompileDependsOn`
