### ISSUE TITLE
RT task not loaded when <TargetFrameworks>net472</TargetFrameworks>

### ISSUE THREAD

**Issue by stan-sz** [dfederm/ReferenceTrimmer#58]
For projects that use plural form of:

```
<TargetFrameworks>net472</TargetFrameworks>
```

while declaring a single target framework cause the RT task to fail to load.

**Comment by stan-sz** [comment]
This could possibly be covered by https://github.com/dotnet/msbuild/issues/1777

**Comment by dfederm** [comment]
> This could possibly be covered by [dotnet/msbuild#1777](https://github.com/dotnet/msbuild/issues/1777)

This would just be a rule to help prevent this. RT should still work with valid (albeit weird) configuration.

For this bug, is it not getting loaded at all, like not for the dispatch to inner builds?

**Comment by dfederm** [comment]
Closing as I'm not able to repro this.
