### ISSUE TITLE
Log framework version in the warning messages

### ISSUE THREAD

**Issue by stan-sz** [dfederm/ReferenceTrimmer#59]
For projects targeting multiple target frameworks, it would be handy to have the information about which target framework the warnings pertains to.

**Comment by stan-sz** [comment]
See related https://stackoverflow.com/questions/59843783/determine-target-framework-inside-a-visual-studio-code-analyzer-roslyn
It looks like a viable approach is to pass that information in an intermediate analyzer file

**Comment by dfederm** [comment]
MSBuild already does this:

![image](https://github.com/dfederm/ReferenceTrimmer/assets/6445614/722fa2fa-dea5-4b17-bdef-06b1e4253160)
