### ISSUE TITLE
Project references used for copying binaries to output are flagged as unneeded

### ISSUE THREAD

**Issue by erikmav** [dfederm/ReferenceTrimmer#61]
In a project graph I have an instance where a test project uses `ProjectReference`s to projects whose outputs - typically executables - are needed in the output path for running tests. Is there a way to signal to ReferenceTrimmer that a specific reference should be ignored? Ignoring `RT0002` in the whole project hides other, real problems. This syntax does not work but was what came to mind to try:

`<ProjectReference Include="..\OtherProj\OtherProj.csproj" NoWarn="RT0002" />`

**Comment by dfederm** [comment]
This seems very reasonable. I knew I needed various knobs to do granular suppressions but hadn't gotten around to it yet.

**Comment by stan-sz** [comment]
`ReferenceOutputAssembly="false"` attribute would solve this problem.

**Comment by erikmav** [comment]
No, disabling `ReferenceOutputAssembly` tells MSBuild to treat the proj reference as a build ordering dependency without binplacing. The purpose of the projref here is to binplace the other project outputs, but we need a way to tell RefTrimmer that it's purposeful for the binplaced files not to be used as assembly references.

**Comment by stan-sz** [comment]
To implement this, we could enrich `DeclaredReferences` with `NoWarn` specific to each entry. The analyzer would need to contain warning suppression code.
