### ISSUE TITLE
Indirect package reference flagged with RT0003 when the local project needs it too

### ISSUE THREAD

**Issue by erikmav** [dfederm/ReferenceTrimmer#62]
An inappropriate `RT0003` appears in 3.1.7 with a pattern like:

Proj1.csproj: `<PackageReference Include="CommandLineParser"/>` (which uses the package reference).

Proj2.csproj - ref to Proj1 but has a class that also uses CommandLineParser:
```
<PackageReference Include="CommandLineParser"/>
<ProjectReference Include="Proj1.csproj" />
```

Result: `warning RT0003: PackageReference CommandLineParser can be removed [Proj2.csproj]`

**Comment by dfederm** [comment]
Are you able to produce a minimal repro? If Proj2 directly has a class which uses the package, it shouldn't error.

Also, does Proj1 matter here? Does the error not happen if the reference to Proj1 were removed?

**Comment by dfederm** [comment]
Closing stale issue. Please reopen if it's still an issue and you have a repro.
