### ISSUE TITLE
Detect dependencies from app.config

### ISSUE THREAD

**Issue by stan-sz** [dfederm/ReferenceTrimmer#70]
An example is a custom [trace listener](https://learn.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-create-and-initialize-trace-listeners), that could be pulled in as a ProjectReference.

**Comment by dfederm** [comment]
Shouldn't something like that be declared as ReferenceOuputAssembly=false?

Understanding app config and any other reflection -based mechanism doesn't seem scalable, and if the reference isn't actually used at compile time, ReferenceOuputAssembly=false seems like a good way to explicitly declare the dependency without the reference.

**Comment by stan-sz** [comment]
app.config contains Assembly names, so logic would be similar to what RT has today.

**Comment by dfederm** [comment]
Closing as these still require valid dependencies to be declared, which they would not be if they solely existed in app config.
