### ISSUE TITLE
On some projects "CollectDeclaredReferencesTask" throws System.NullReferenceException

### ISSUE THREAD

**Issue by bantza** [dfederm/ReferenceTrimmer#71]
I have a C# solution and I added ReferenceTrimmer nuget package to all the projects. 3 out of 9 projects give following kind error when compiling. When removing ReferenceTrimmer from those projects they compile fine. I can't think of anything common with these three projects that other projects don't have. 

> ------ Build started: Project: StickerPrinting, Configuration: Debug x64 ------
C:\Users\bantza\.nuget\packages\referencetrimmer\3.1.22\build\ReferenceTrimmer.targets(24,5): error MSB4018: The "CollectDeclaredReferencesTask" task failed unexpectedly.
&nbsp;&nbsp;System.NullReferenceException: Object reference not set to an instance of an object.
&nbsp;&nbsp;&nbsp;&nbsp;at ReferenceTrimmer.Tasks.CollectDeclaredReferencesTask.GetPackageInfos()
&nbsp;&nbsp;&nbsp;&nbsp;at ReferenceTrimmer.Tasks.CollectDeclaredReferencesTask.Execute()
&nbsp;&nbsp;&nbsp;&nbsp;at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
&nbsp;&nbsp;&nbsp;&nbsp;at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

I'm using VisualStudio.17.Release/17.7.3+34024.191 and the projects in the solution are .netframework4.8 and .netstandard2.0. All three that are failing are .netframework4.8, but there are also other .netframework4.8 projects that are not failing.

**Comment by dfederm** [comment]
Ah, looks like the problem is with legacy-style (non SDK) projects. I'm only looking for `$(TargetFramework)` and not `$(TargetFrameworkVersion)`. This seems pretty easy to fix.
