### ISSUE TITLE
Suppress a specific package reference?

### ISSUE THREAD

**Issue by martincostello** [dfederm/ReferenceTrimmer#91]
Discovered this project recently and just tried it out in a project where I add the `GitHubActionsTestLogger` NuGet package to all of my test projects to report dotnet test results to GitHub Actions workflow logs.

This dependency isn't used to compile the code at all, but is used to copy the library to the output folder so that I can enable its usage with the `--logger GitHubActions` argument to `dotnet test`.

Because of this, the build fails (because I use errors as warnings) with for `RT0003` in all of my test projects.

How do I suppress this specific instance of the false-positive?

**Comment by martincostello** [comment]
My bad - I was using "suppress" as the verb when I was searching the documentation, not "disable". The answer to my question is in the README 🤦

https://github.com/dfederm/ReferenceTrimmer/blob/ba5ec8aa06523ea332db776adda66f9add7ead80/README.md?plain=1#L107-L112

**Comment by dfederm** [comment]
@martincostello glad you were able to figure it out. However it does sound like your scenario might be best suited by a `PackageDownload` instead of a `PackageReference`. Just something to consider.

**Comment by martincostello** [comment]
Thanks for the info - TIL about `PackageDownload`. I'm not sure it'll play nice with CPVM+Dependabot though as I need to wrap the version with `[]`s and I don't think dependabot deals with that for NuGet (at least I've not seen it before).
