### ISSUE TITLE
Support .editorconfig

### ISSUE THREAD

**Issue by stan-sz** [dfederm/ReferenceTrimmer#93]
Because ReferenceTrimmer uses `Location.None` when issuing warnings and due to https://github.com/dotnet/roslyn/issues/37876, warnings cannot be controlled with `.editorconfig`. Such ability would be useful for large repos where reference cleanup can be done folder-wise (e.g. repo-wide suggestion, per-folder enforced via error/warning).

**Comment by dfederm** [comment]
As we have a test for this, I'm assuming this is no longer an issue.
