### ISSUE TITLE
Rebuild fails even after removing projectreference

### ISSUE THREAD

**Issue by stijnexterAM** [dfederm/ReferenceTrimmer#98]
Build -> fails because of unneeded projectreference
Remove unneeded projectreference
Rebuild -> still fails with the same error

If solution is reopened, and rebuild -> the error is gone

VS2022 (17.9.7, 64bit)
Dotnet 8.0

**Comment by dfederm** [comment]
Would you be able to provide a minimal repro?

**Comment by dfederm** [comment]
Closing stale issue
